// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9YUkIpfby3cayASs7EKIMNTngjIz8-4Y',
    appId: '1:235851995201:web:08a3b8c66acc5a532d8ec0',
    messagingSenderId: '235851995201',
    projectId: 'wishonit-33f0a',
    authDomain: 'wishonit-33f0a.firebaseapp.com',
    storageBucket: 'wishonit-33f0a.firebasestorage.app',
    measurementId: 'G-J4DRG82W04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEH8LVKMlbn8mFM84O7evT_lKb-iG74L4',
    appId: '1:235851995201:android:275a96ad5cc774872d8ec0',
    messagingSenderId: '235851995201',
    projectId: 'wishonit-33f0a',
    storageBucket: 'wishonit-33f0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYH_vV0sbyE2dVILy0nG1ZlLrt6mgmyVw',
    appId: '1:235851995201:ios:794b6c7c5b2850bd2d8ec0',
    messagingSenderId: '235851995201',
    projectId: 'wishonit-33f0a',
    storageBucket: 'wishonit-33f0a.firebasestorage.app',
    iosClientId: '235851995201-4g71tl2r320i8dphlk47n8kdp2qqs3jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.wishonit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYH_vV0sbyE2dVILy0nG1ZlLrt6mgmyVw',
    appId: '1:235851995201:ios:794b6c7c5b2850bd2d8ec0',
    messagingSenderId: '235851995201',
    projectId: 'wishonit-33f0a',
    storageBucket: 'wishonit-33f0a.firebasestorage.app',
    iosClientId: '235851995201-4g71tl2r320i8dphlk47n8kdp2qqs3jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.wishonit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9YUkIpfby3cayASs7EKIMNTngjIz8-4Y',
    appId: '1:235851995201:web:cee7a43b2ac399b42d8ec0',
    messagingSenderId: '235851995201',
    projectId: 'wishonit-33f0a',
    authDomain: 'wishonit-33f0a.firebaseapp.com',
    storageBucket: 'wishonit-33f0a.firebasestorage.app',
    measurementId: 'G-JS9HZG9YD3',
  );
}
